### ISSUE TITLE
Is this repo actively being maintained?

### ISSUE THREAD

**Issue by melodykramer** [CodeForAsheville/email-all-nc-legislators#1]
I have a few suggestions to improve the functionality for users. Are you still maintaining the repo? Happy to pitch in. (I live in Carrboro.)

**Comment by ejaxon** [comment]
Hi, Melody, not too sure about 'actively' but this is obviously a good time to update it. Suggest away and help welcome!

**Comment by conantp** [comment]
Well, we haven't made any updates recently, but this tool has seen wide use in response to HB2. 

We had over 2500 people use it yesterday, and over 1000 already today. People are really excited about this tool and have suggested some updates - we absolutely would love to have your help Melody!
